---
title: "Predicting the Probability that a Horse Wins a Race in Hong Kong"
author: "Matthew Lewis"
date: "4/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


--
## Data Import

```{r}
hk <- read.csv("hk.csv")
```


--
## Data Cleaning and Exploration

```{r}
hk$won <- as.logical(hk$won)

hk$date <- NULL

hk$position_sec5 <- NULL
hk$position_sec6 <- NULL

hk$behind_sec5 <- NULL
hk$behind_sec6 <- NULL

hk$time5.x <- NULL
hk$time6.x <- NULL

hk$sec_time5 <- NULL
hk$sec_time6 <- NULL
hk$sec_time7 <- NULL

hk$time5.y <- NULL
hk$time6.y <- NULL

hk$time7 <- NULL

hk$place_combination4 <- NULL

hk$place_dividend4 <- NULL

hk$win_combination2 <- NULL
hk$win_dividend2 <- NULL

hk$horse_gear<-NULL
hk$position_sec4<-NULL
hk$behind_sec4<-NULL
hk$time4.x<-NULL
hk$time4.y<-NULL
hk$sec_time4<-NULL
hk$place_dividend3<-NULL
hk$place_combination3<-NULL

hk$horse_ratings <- as.factor(hk$horse_ratings)
hk$place_odds[is.na(hk$place_odds)] <- mean(hk$place_odds, na.rm = TRUE)
hk$prize[is.na(hk$prize)] <- mean(hk$prize, na.rm = TRUE)
```

```{r}
movetolast <- function(data, move) {
  data[c(setdiff(names(data), move), move)]
}

hk <- movetolast(hk, c("won"))
```


```{r}
sapply(hk, function(x) sum(is.na(x)))
```

```{r}
hk$horse_country<-ifelse(hk$horse_country=="AUS",0,
                         ifelse(hk$horse_country=="NZ",1,
                                ifelse(hk$horse_country=="IRE",2,
                                       ifelse(hk$horse_country=="GB",3,
                                              ifelse(hk$horse_country=="USA",4,5)))))
hk$horse_type<-ifelse(hk$horse_type=="Gelding",0,1)
hk$venue<-as.numeric(hk$venue)
hk$config<-ifelse(hk$config=="A",0,
                  ifelse(hk$config=="A+3",1,
                         ifelse(hk$config=="B",2,
                                ifelse(hk$config=="B+2",3,
                                       ifelse(hk$config=="C",4,5)))))
hk$going<-ifelse(hk$going=="FAST",0,
                 ifelse(hk$going=="GOOD",1,
                        ifelse(hk$going=="GOOD TO FIRM",2,
                               ifelse(hk$going=="GOOD TO YIELDING",3,
                                      ifelse(hk$going=="SLOW",4,
                                             ifelse(hk$going=="SOFT",5,
                                                    ifelse(hk$going=="WET FAST",6,
                                                           ifelse(hk$going=="WET SLOW",7,
                                                                  ifelse(hk$going=="YIELDING",8,9)))))))))
```

```{r}
str(hk)
summary(hk)
```


--
## Data Visualization

```{r}
library(ggplot2)

type_plot <- ggplot(data = hk, aes(x = lengths_behind, y = result))
type_plot + geom_jitter(alpha = 1)
```

```{r}
plot(x = hk$actual_weight, y = hk$result, main = "Result vs. Weight", xlab = "Weight",  ylab = "Result")

result_weight <- round(sort(tapply(hk$result, hk$actual_weight, mean, na.rm = TRUE), TRUE), 3)
as.matrix(result_weight)
```

```{r}
plot(x = hk$position_sec1, y = hk$result, main = "Result vs. Start", xlab = "Start",  ylab = "Result")

result_start <- round(sort(tapply(hk$result, hk$position_sec1, mean, na.rm = TRUE), TRUE), 3)
as.matrix(result_start)
```

```{r}
age_won <- table(hk$horse_age, hk$won)
age_won
plot(age_won) # 4 year old horses tend to win more on average than other ages

pos1_won <- table(hk$position_sec1, hk$won)
pos1_won
plot(pos1_won) # horses in the lead at first tend to win most races

pos2_won <- table(hk$position_sec2, hk$won)
pos2_won
plot(pos2_won)

pos3_won <- table(hk$position_sec3, hk$won)
pos3_won
plot(pos3_won) # by the third turn, there is a greater than 50% chance that the lead horse wins the race

country_won <- table(hk$horse_country, hk$won)
country_won
plot(country_won) # Argentinian and South African horses tend to win a higher percentage of races than other countries
```


--
## Logistic Regression Models

### Logistic Regression
```{r}
logistic1 <- glm(won ~ place_odds + position_sec1 + position_sec2 + position_sec3 + distance, data = hk, family = "binomial")
summary(logistic1)

logistic2 <- glm(won ~ place_odds + position_sec1 + position_sec2 + position_sec3 + horse_age + declared_weight, data = hk, family = "binomial")
summary(logistic2)

logistic3 <- glm(won ~ place_odds + position_sec1 + position_sec2 + position_sec3 +  horse_country, data = hk, family = "binomial")
summary(logistic3)

logistic4 <- glm(won ~ place_odds + position_sec1 + position_sec2 + position_sec3 +  horse_type, data = hk, family = "binomial")
summary(logistic4)

logistic5 <- glm(won ~ place_odds + position_sec1 + position_sec2 + position_sec3 +  horse_ratings, data = hk, family = "binomial")
summary(logistic5)

logistic6 <- glm(won ~ place_odds +  distance + horse_age + declared_weight + horse_country + horse_type, data = hk, family = "binomial")
summary(logistic6)

logistic7 <- glm(won ~ distance + horse_age + declared_weight + horse_country + horse_type, data = hk, family = "binomial")
summary(logistic7)
```


## Predictive Models

### Normalize and Structure Data
```{r}
# normalizing data
hk_norm <- as.data.frame(model.matrix(~.-1, hk))

normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}
```

```{r}
hk_norm <- as.data.frame(lapply(hk_norm[1:78], normalize))
```

```{r}
table(hk_norm$won)
```

```{r}
# separate data into test and train
train_x <- hk_norm[1:60000, -ncol(hk_norm)]
test_x <- hk_norm[60001:79447, -ncol(hk_norm)]
train_y <- hk_norm[1:60000, ncol(hk_norm)]
test_y <- hk_norm[60001:79447, ncol(hk_norm)]

alpha_train <- hk_norm[1:60000, ]
alpha_test <- hk_norm[60001:79447, ]
```

### kNN

```{r}
library(class)
hk_norm_pred <- knn(train = train_x, test = test_x, cl = train_y, k = 7) # no missing values are allowed
library(gmodels)
CrossTable(x = test_y, y = hk_norm_pred, prop.chisq = FALSE)
```

```{r}
library(caret)
confusionMatrix(factor(hk_norm_pred), factor(test_y))
```

